---

- name: Add Zip
  apt:
    name: zip
    state: present
  become: true

- name: Add SDK
  ansible.builtin.shell:
    cmd: sudo curl -s https://get.sdkman.io | bash
  become: true

- name: Install JAVA
  ansible.builtin.shell:
    cmd: '. /home/ubuntu/.sdkman/bin/sdkman-init.sh && sdk install java 8.0.402-librca'
  become: true

- name: JIRA | Ensure JIRA group
  group:
    name: "{{ jira_group }}"
  become: true

- name: JIRA | Ensure JIRA user
  user:
    name: "{{ jira_user }}"
    group: "{{ jira_group }}"
    shell: /bin/bash
  become: true

- name: JIRA | Create path for JIRA's folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
  with_items:
    - "{{ jira_home }}"
    - "{{ jira_download_dir }}"
    - "{{ jira_installation_dir }}"
  become: true

- name: JIRA | Link attachments folder in case not using default one
  file:
    src: "{{ jira_home }}/data/attachments"
    dest: "{{ jira_attachments_dir }}"
    state: link
  when: jira_attachments_dir != jira_attachments_default_dir
  become: true

- name: JIRA | Download package
  get_url:
    dest: "{{ jira_download_dir }}/{{ jira_package }}"
    url: "{{ jira_installation_url }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
  register: jira_downloaded
  become: true

- name: JIRA | Unarchive package
  unarchive:
    src: "{{ jira_download_dir }}/{{ jira_package }}"
    dest: "{{ jira_installation_dir }}"
    remote_src: yes
    extra_opts: --strip-components=1
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
  when: jira_downloaded.changed
  tags:
    - skip_ansible_lint
  become: true

- name: JIRA | Optional JDBC connectors
  include_tasks: jdbc.yml
  when: jira_database_configuration
  tags:
    - jdbc
