---

- name: JIRA | Configuring service
  systemd:
    name: "{{ jira_service_name }}"
    state: "{{ jira_service_state }}"
    enabled: "{{ jira_service_enabled }}"
    daemon_reload: yes
  become: true
